### ISSUE TITLE
Add an energy minimization method

### ISSUE THREAD

**Issue by davidcortesortuno** [computationalmodelling/fidimag#107]
We should implement an energy minimizer algorithm such as the conjugate gradient method that is implemented in OOMMF (see http://aip.scitation.org/doi/10.1063/1.4981902 , I think OOMMF allows to use any of the `beta` factors from eqs 13, 14 or 15)

Or the steepest descent method implemented in Mumax3. They use this recent publication

http://www.cms.tuwien.ac.at/media/pdf/publications/jap-115-17D118-2014.pdf

with the most basic criteria to alternate between the two possible `tau` factors (we could also try to use a batter criteria).

I think this should be a nice improvement since the LLG sometimes has problems with finding some metastable states. I've seen this from the NEBM simulations, where the algorithm is usually more effective in finding lower energy states than those found with the LLG.

**Comment by davidcortesortuno** [comment]
A minimiser class was implemented recently. We can add more minimisers in the future

**Comment by fangohr** [comment]
Very nice. Should we have an example (notebook) that features prominently in the documentation (https://fidimag.readthedocs.io/en/latest/index.html) to showcase the feature?

**Comment by davidcortesortuno** [comment]
Done. I just show the example for the atomistic code since the micromagnetic one has some issues, but it's there. I'll close the issue and maybe we can raise another in case someone wants to test the micromagnetic SD
