### ISSUE TITLE
Update docker containers

### ISSUE THREAD

**Issue by Fellow-baka** [computationalmodelling/fidimag#109]
Hi, it seems like docker versions of fidimag was updated about 2 years ago and currently non compatible with documentation ([fidimag.readthedocs.io](fidimag.readthedocs.io)).

**Comment by davidcortesortuno** [comment]
Thanks, we will take a look to the Docker files. Fo now you can refer to the Dockerfile used for Binder (in the main directory) which is compatible with the latest Fidimag version
