### ISSUE TITLE
3D macro solver for magnetostatic problems

### ISSUE THREAD

**Issue by berceanu** [computationalmodelling/fidimag#110]
![10mm_16mag00](https://user-images.githubusercontent.com/4405658/36632170-a7a4de3c-198b-11e8-8dd2-5cd53400cbe3.PNG)
I apologize for being slightly off-topic here, but does fidimag support solving 3D magnetostatic problems? To get some more context, I am attaching a plot created with Poisson Superfish.
Unfortunately that code is 2D and windows-only, and we are looking for 3D capability and Linux compatibility. There is Comsol of course, but I restricted myself to FOSS.

I did a quick search and came up with the following alternatives:
[xfemm](https://sourceforge.net/p/xfemm/wiki/Home): 2D, Linux, Octave interface
[Radia](http://www.esrf.eu/Accelerators/Groups/InsertionDevices/Software/Radia): 3D, win-only, Mathematica interface
[FEniCS](https://fenicsproject.org), 3D, Linux, Python interface, but seems to be a general FEM solver without built-ins for electro/magneto-statics

Are there plans to implement this in fidimag or could you please point me in the right direction?

Thank you very much!

**Comment by rpep** [comment]
Hi @berceanu - it's Ryan Pepper here - I answered your question the other day on the FEniCs Slack.

I can try and build an example for you that does this in our software, but it might be a bit clunky - it's not really what it's designed for, as we use it to model time evolution. I think it's possible though.

**Comment by berceanu** [comment]
Hi @rpep ! 
I don't think that will be necessary, thanks! I was just wondering is someone might know a code dedicated to this. I think Flux3D would do the job, but it doesn't seem to be freely available.

I remember you pointed me towards BEM++, I wrote a message on their mailing list.

> Bempp currently does not do magnetostatic. However, we have just started a research council project > for which we need the kernels So this will soon be coming.

I also wrote to the mumax folks, and they suggested

> 1. magnum.fe (http://micromagnetics.org/magnum.fe/, https://github.com/micromagnetics
> /magnum.fe) based on FEniCS. FOSS version last updated 2015, now commercial only.
> 2. Nmag (http://nmag.soton.ac.uk/nmag/), last updated 2012. (mailing list somewhat alive?)
> 3. magpar (http://www.magpar.net/FrontPage), last updated 2010.

But these all seem to be micromagnetic codes, not exactly what we're after.
