### ISSUE TITLE
Add method to change driver with a simulation

### ISSUE THREAD

**Issue by davidcortesortuno** [computationalmodelling/fidimag#111]
Sim objects need a `set_driver` method to update the driver in case one needs to change/update the LLG equation to simulate different dynamics with the same `Sim` object

Another option would be to separate the driver completely from the `Sim` class, however this would require a major refactoring. Maybe for Fidimag 3?

**Comment by rpep** [comment]
Is this really necessary?

You can just change parameters mid way through the simulation, e.g. the spin torque ones, and reinitialise the Sim object

**Comment by davidcortesortuno** [comment]
But you have to create a new Sim object to change the driver, say `llg` to `llg_stt` (we have different LLG eqs in separate classes). Otherwise you have to manually pass the parameters (mesh, etc) to `driver.llg_stt.LLG_STT`, which is not very intuitive

**Comment by rpep** [comment]
No, what I mean is - create an object with llg_stt. But set the parameters to zero initially (so still solving LLG) and change them at some later time. It shouldn't have a measurable performance impact because Demag is the slowest part of the code.

**Comment by rpep** [comment]
For this issue, what I meant here was that you can do:

```
sim = sim(mesh, driver='llg_stt')
sim.j = (0, 0, 0)
sim.P = 0
# Run some simulation, etc

sim.j = (1e12, 0, 0)
# run the simulation more.
```
If you're concerned about performance we can just add an if statement to check if the current is non-zero

**Comment by rpep** [comment]
As alternative will close now
