### ISSUE TITLE
example isolated_skyrmion is not workding

### ISSUE THREAD

**Issue by zhouxzh** [computationalmodelling/fidimag#128]
I just install the docker fidimag/notebook.
I just run the example isolated_skyrmion.
I just find out the error: 'LLG' object has no attribute 'driver'.
I also try another example in the document, and I find the similar error.
It seem the code changed quite a lot after these examples were created.

**Comment by rpep** [comment]
Hi Zhou,

We'll assume this is fixed now - please let us know if you're still having trouble,

Best wishes,
Ryan
