### ISSUE TITLE
Integrate IPython notebook testing into tutorial notebooks.

### ISSUE THREAD

**Issue by mvousden** [computationalmodelling/fidimag#13]
Use nbval (https://github.com/computationalmodelling/nbval) to test IPython notebooks in /doc/ipynb. Configure notebooks to pass these tests by, for example, ignoring image output when running tests.

**Comment by mvousden** [comment]
This is being resolved on branch ENH-013-notebook-tests. The state is that nbval is that the tests only differ during relaxation runs. Plots are currently being ignored.

**Comment by fangohr** [comment]
This should also be part of the continuous integration. We may need a new issue for this.
