### ISSUE TITLE
Issues with plot_m import error and sim.driver attribute error

### ISSUE THREAD

**Issue by researchAM** [computationalmodelling/fidimag#131]
The following error was generated when I am trying to import plot_m from fidimag.common::

**ImportErrorTraceback (most recent call last)
<ipython-input-8-afc2cbcd49d3> in <module>()
      2 from fidimag.common import CuboidMesh
      3 from fidimag.micro import UniformExchange, Demag, DMI
----> 4 from fidimag.common import plot_m
      5 get_ipython().magic('matplotlib inline')

ImportError: cannot import name 'plot_m'**

And also, use of sim.driver.alpha/gamma//do-precession/relax is generatng the following error::

AttributeError: 'LLG' object has no attribute 'driver'

Kindly help me resolve these issues.

**Comment by ww1g11** [comment]
Hi, I have moved the plot_m function out of the default  modules of fidimag to reduce its dependency (otherwise fidimag will import matplotlib).  Still, you can use

`from fidimag.common.plt_helper import plot_m`

to import plot_m.

For the error 

> AttributeError: 'LLG' object has no attribute 'driver'

could you please show the code you  are using?

**Comment by researchAM** [comment]
I was using the code from the exmaple given in Fidimag documentation, fidimag basic simulation, https://fidimag.readthedocs.io/en/latest/ipynb/tutorial-basics.html.

**Comment by ww1g11** [comment]
are you using the newest version of fidimag? In the early version, the Sim class actually is an LLG class and it indeed has no attribute 'driver'. After Aug 2016 the sim class should have the 'driver' attribute.

**Comment by researchAM** [comment]
I am basically a novice. I have blindly followed instructions given in this link- "https://fidimag.readthedocs.io/en/latest/ipynb/tutorial-docker-container.html" regarding running Fidimag inside a Docker container. Is there any other way to install Fidimag?

**Comment by ww1g11** [comment]
Yes, the Docker file is outdated.

It's not hard to install fidimag in a linux system or mac, but it is not easy to install it in windows I think.

**Comment by researchAM** [comment]
I am using Linux Mint 19.1 64 bit Tessa system. Kindly give me a guideline to install Fidimag in this system.

**Comment by ww1g11** [comment]
Here is a guideline: https://github.com/computationalmodelling/fidimag/blob/master/doc/install.rst
Basically, you need to install FFTW, Sundials and other python packages such as numpy, pyvtk etc,
as can be seen in the `ubuntu_install_script.sh`:

>sudo bash install-ubuntu-packages.sh
>sudo bash install-python-packages.sh
>bash install-fftw.sh
>bash install-sundials.sh
>make

and finally append the fidimag path to  PYTHONPATH by adding the following to your ~/.bashrc 
>export PYTHONPATH=/path/to/fidimag:$PYTHONPATH

good luck~

**Comment by researchAM** [comment]
Thank you.
