### ISSUE TITLE
doubt about features implemented on Fidimag

### ISSUE THREAD

**Issue by Mc210** [computationalmodelling/fidimag#141]
Hi,

I would like to know if this code allow to put 3D current using Zhang-Li torque (spatially variable like mumax3), a variable uniaxial anisotropy like radial anisotropy or something like this and the bulk or interfacial DMI. 

Thanks so much

**Comment by davidcortesortuno** [comment]
Hi, those 3 properties can be used in Fidimag. For the Zhang-Li STT you can set a function for the current. In the case of anisotropy, you can also pass a space dependent function to define the anisotropy vectors (in your case you would have to compute the radial direction as function of space, which should be straightforward. 
And regarding DMI, you have the choice of interfacial, bulk and D_2d group symmetry DMI. You can also define your own DMI by implementing the finite difference version of the DMI term.

The doctrings in the corresponding energy terms in https://github.com/computationalmodelling/fidimag/tree/master/fidimag/micro might be of help. For STT, check the `llg_stt` file. 

To set a specific driver, when creating a simuation yo do something like `sim = fidimag.micro.Sim(mesh, driver='llg_stt')` and then set the current functions as `sim.driver.jx = ...`

**Comment by Mc210** [comment]
That is great,

Thanks you

**Comment by davidcortesortuno** [comment]
That depends on the material you are analysing, the magnetic structures you are studying and the memory available in your machine. In an atomistic simulation you have a lattice spacing of a few Angstrom, thus you can do the maths to check how many atomic positions you need for a system of a few nanometres or larger in size.
