### ISSUE TITLE
Import Error - can`t find common_clib

### ISSUE THREAD

**Issue by mrtalkingbadger** [computationalmodelling/fidimag#142]
Hello all, after following the installtion instructions, the program fails to import fidimag while giving the following message:
"
Could not load Fidimag extenions ….
...
...

Exception Error Message
-----------
No module named common_clib 

System Info
------------
Architecture: x86_64
Platform: Linux-4.19.0-8-amd64-x86_64-with-debian-10.3
Processor:

"
I tried all the suggestions given in the error text. Does anyone has an idea why this is still failing? 
Some advice would be great!

Best, 
Thomas

**Comment by davidcortesortuno** [comment]
Hi, how did you install Fidimag? You need `cython` (recommended installing via `pip`) and some other Python libraries shown in the documentation. To build FFTW and Sundials, go to the `build` folder and run the corresponding bash scripts for these two libraries. Then go to the main folder, and do `make`, that will compile the Cython modules. Finally, add Fidimag to the Python path.

You can also see these same steps from the `Dockerfile` in the main folder

**Comment by mrtalkingbadger** [comment]
Thank you for the fast Reply!
It is working now, the Problem was, that i used python 2 as Default, with python 3 it is working now!
Thanks!
Best,
Thomas
