### ISSUE TITLE
Problems finding examples

### ISSUE THREAD

**Issue by thomasbrianwinkler** [computationalmodelling/fidimag#145]
Hello,
i was shifting through the examples, but was not able to found examples for some methods:

Could you provide just 2 lines of fidimag code examples on:

a) how to read a file (npy or omf).
b) how to compute topological winding number (if possible)
c) how to change zeeman field strength after initialization.

Best,
Thomas

**Comment by davidcortesortuno** [comment]
Hi,

a) What do you need the `npy` files for? Fidimag uses `npy` to store the magnetisation or spin directions, which you can load via the `sim.set_m` method, as `sim.set_m(np.load(my_spins.npy))` for example

b) The `sim` class contains the topological charge calculation, if you have a reasonable magnetic structure you just call `sim.skyrmion_number`. The methods differ in the micro or atomistic cases so check the docstring of the functions. Also take a look at https://github.com/computationalmodelling/fidimag/blob/master/fidimag/atomistic/sim.py for the atomistic case for example

c) You can update it by updating the `Zeeman` interaction class which is added to the `sim` class when you add a `Zeeman` interaction:

```python
Zeeman_int = sim.get_interaction('Zeeman')  # get Zeeman interaction class
Zeeman_int.update_field((0.0, 0.0, B_sweep * 1e-3))
```

**Comment by thomasbrianwinkler** [comment]
Hello,
thanks a lot for the small code snippets. That is all i needed!
Best,
Thomas
