### ISSUE TITLE
No change in TimeZeeman in V3.0

### ISSUE THREAD

**Issue by dasikashishir** [computationalmodelling/fidimag#147]
I downloaded the 3.0V. The changelog mentions that we can have arbitrary function for timezeeman of the form
 ```
 def time_function(pos, t):
      x, y, z = pos
      # some calculation of Bx(pos, t), By(pos, t), Bz(pos, t)
      return (Bx, By, Bz)
```
  But I get ```missing 1 required positional argument: 't'``` error. Also the version fidimag.__version__ shows 0.2 instead of 3.0

**Comment by davidcortesortuno** [comment]
Hi, the code accepts `H0` as the field (which can be space dependent function) and a time function, as shown here https://github.com/computationalmodelling/fidimag/blob/master/fidimag/micro/zeeman.py 
How are you actually calling the function?
The version is definitely wrong so we will update the code

**Comment by rpep** [comment]
No response from user
