### ISSUE TITLE
docker startup problem

### ISSUE THREAD

**Issue by code-whale** [computationalmodelling/fidimag#148]
Hello, I built the fidimag container under the main file according to your answer in question 143, but after I ran the docker run command, the program terminated after only one run. Do you know what caused this?
![Uploading 截屏2020-10-01 上午11.33.28.png…]()

**Comment by davidcortesortuno** [comment]
Hi, can you post the output/error messages of the commands you are running? The image you posted did not upload well I think

**Comment by code-whale** [comment]
@davidcortesortuno Hi,Well, I first downloaded your repository and used ```docker build-t fidimag. ```Fidimag container is built, but the container cannot run continuously after I input ```docker dun-v pwd :/ io -p 30008:8888 fidimag```. I modify the instruction to ```docker run -dit -p 30008:8888 fidimag```, and it can run continuously but cannot interact with the local file. Do you know how to correct this situation

**Comment by davidcortesortuno** [comment]
Have you tried with: `docker run -v .:/io -p 30008:8888 fidimag` ?

**Comment by code-whale** [comment]
@davidcortesortuno ，I have also tried the instructions you said, but it seems that it can only let me run the simulation in a specific folder. I hope the simulation file I created can be in my computer. Is there any way to do this?
<img width="1261" alt="截屏2020-10-01 下午9 54 36" src="https://user-images.githubusercontent.com/61874432/94818442-b665d380-0430-11eb-8dca-0ab7eea5bcc8.png">

**Comment by davidcortesortuno** [comment]
When you mount the volume with `-v .:/io` it tells Docker that the files in the directory where you currently are (that's the dot `.`), are mounted on the `io` folder of the Docker container. Any file produced in a simulation within the Docker container, should then appear in the folder where you currently are. In other words, when you run the simulation, the output files should appear in your computer in the directory where you executed Docker

**Comment by davidcortesortuno** [comment]
Sometimes, it is better to run Fidimag from a Python script, say `my_script.py`, in that case you can call

```
docker run -v .:/io fidimag bash -c "python my_script.py
```

which will execute the Python script in the Docker container

**Comment by code-whale** [comment]
@davidcortesortuno, I try to input the following instructions, ```docker run -v /Volumes/Whale/ fidimag-master :/ io -p 30008:8888 fidimag```, but the container can only perform on the volume and close automatically. I think it should use ```docker run-v /Volumes/Whale/fidimag-master:/ io -dit -p 30008:8888 fidimag``` to keep it running. But in this case, I use ```jupyter notebook -- IP 0.0.0.0 --no-browser --allow-root``` after entering ```localhost: 30008``` in the browser, I need to type Token to run jupyter Notebook and the files I simulate still can not be displayed in my computer, I do not know the reason for this situation, thank you very much for your help!
<img width="641" alt="截屏2020-10-01 下午10 30 50" src="https://user-images.githubusercontent.com/61874432/94824319-76561f00-0437-11eb-807a-9ed771aefd41.png">

**Comment by davidcortesortuno** [comment]
With the command 

```
docker run -p 30008:8888 -ti -v $(pwd):/io -p 30008:8888 fidimag
```

(or instead `$(pwd)` specify the folder as you do) you start Docker in interactive mode, then you can call `jupyter notebook` and running the notebooks should produce the simulation files in the specified volume because you already mounted it with `-v`. In other case I'm not sure, you might have to look into Docker.

**Comment by rpep** [comment]
Is /Volumes/Whale an external drive or your main system drive? And are you using macOS Catalina? I know there have been some changes in this version on permissions that I’ve run into with Docker

**Comment by code-whale** [comment]
@davidcortesortuno ,Thank you very much patience to help, but unfortunately I always can't create simulation files in the specified path, perhaps I need to further study the docker use, I found that no matter how I modify command, terminal display ```magnetism @ aab08ff54d21: ~ / doc/ipynb $```, I think may be associated with this
<img width="775" alt="截屏2020-10-02 上午8 14 46" src="https://user-images.githubusercontent.com/61874432/94875404-58b0a600-0487-11eb-9901-1d9334212d7c.png">

**Comment by code-whale** [comment]
@rpep Hello, Whale is an external drive, but I also made the same attempt in the drive of the main system, but there was no obvious difference in the result. I used macOS Catalina10.15.6. In some instructions, Docker did have permission problems, and in the screenshot in the last reply, there was no right to access, thanks for your reply!
