### ISSUE TITLE
Launch Binder Error

### ISSUE THREAD

**Issue by melissa-e-henderson** [computationalmodelling/fidimag#151]
Hi, I have been using Fidimag (launched through the github binder) over the past little while to generate some skymrion simulations. Recently however, whenever I launch the binder it will say the "notebook list is empty", and when I go to create a new notebook it will give me a permission denied error. I was previously able to run the simulations without any trouble by launching the binder; do you know what may be causing this?

Thanks

**Comment by davidcortesortuno** [comment]
Hi, maybe the Binder team updated something we are not aware of, possibly in their filesystem. The Binder system is mostly for testing Fidimag, but it is not intended for production. Have you tried to install Fidimag in your computer? That might be better

**Comment by rpep** [comment]
No response from user
