### ISSUE TITLE
Update to modern SUNDIALS

### ISSUE THREAD

**Issue by rpep** [computationalmodelling/fidimag#152]
Sundails > 3.0 is a different API but migrating needs doing because it is diverging further and old SUNDIALS blocks a few things (e.g. adding GPU support).

**Comment by davidcortesortuno** [comment]
We could try to use `odes` https://github.com/bmcage/odes , which has wrappers to the newest sundials versions

**Comment by rpep** [comment]
@davidcortesortuno i think MA worked on this some time ago

**Comment by davidcortesortuno** [comment]
I just updated the Sundials cython wrapper to work with Sundials 6. All tests pass now :)
We are also now pulling Sundials from their new Github repo. We might need to update the license terms.
I will close this issue, as it is solved for now

**Comment by rpep** [comment]
Woo!
