### ISSUE TITLE
Problems of  spatially varying DMI

### ISSUE THREAD

**Issue by yuanshh** [computationalmodelling/fidimag#155]
Dear fidimag team:
How can I add a spatially varying DMI in atomistic simulation ? I have tried to do this with a function like this :
![image](https://user-images.githubusercontent.com/64522903/117431951-60c04f00-af5c-11eb-8a41-189abcb8fcc4.png)
but it returns :
![image](https://user-images.githubusercontent.com/64522903/117431899-54d48d00-af5c-11eb-82b2-d89b979b09c5.png)

**Comment by davidcortesortuno** [comment]
Hi, I think you found a bug in the code. Thanks for reporting it. In the `fidimag/atomistic/dmi.py` function, in the section of the code (line 133) we have

```
        elif self.dmi_type == 'interfacial':

            clib.compute_dmi_field_interfacial(m,
                                               self.field,
                                               self.mu_s_inv,
                                               self.energy,
                                               self.D,
                                               self.neighbours,
                                               self.n,
                                               self.n_ngbs,
                                               self.n_ngbs_dmi,
                                               self.DMI_vector
                                               )
```
where `self.D` must be `self._D`. I'll commit the changes

**Comment by davidcortesortuno** [comment]
Hey, I realized DMI doesn't accept spatially varying DMI for interfacial systems, we can implement it maybe next week. Spatial only works for bulk DMI

**Comment by yuanshh** [comment]
Hi, @davidcortesortuno 
Thanks for your reply! I have updated the 'dmi.py' file, but unfortunately it returns another error:
![图片](https://user-images.githubusercontent.com/64522903/118460700-86eda800-b72f-11eb-91a0-9d6bcc778e5e.png)
And when I use the bulk type, it also has an error:
![图片](https://user-images.githubusercontent.com/64522903/118461223-07140d80-b730-11eb-87a0-50b3ed4c0a04.png)

**Comment by davidcortesortuno** [comment]
Hi, I just updated the documentation and DMI classes to allow spatial dependence of the interfacial DMI. Can you build Fidimag again and test if it now works for you?

**Comment by yuanshh** [comment]
Hi, @davidcortesortuno 
I have rebuilt Fidimag and use the function I used before. And it returns:
![图片](https://user-images.githubusercontent.com/64522903/118750632-5c683000-b892-11eb-9664-6ed132ac05fe.png)
It is the same as the error in bulk type.

**Comment by davidcortesortuno** [comment]
Ah, the error is because your DMI function should return 6 values, which are the DMI values for every neighbour (the neighbour list depends on the mesh you use, check the documentation for the DMI function), something like

```python
def D_pos(r):
    x, y, z = r
    if x < L/2:
        return np.zeros(6)
    else:
        return np.ones(6.) * D
```

However you might also set these values at the boundary. At `x = L/2 - dx` where `dx` is a lattice unit, you might need something something like `[0, D, 0, 0, 0, 0]` since the neighbour at `+x` should have a `D` strength DMI. Similarly at `x=L/2 + dx` you might need something like `[D, 0, D, D, D, D]`.
This is currently how we have implemented spatial varying DMI but we will think if there might be a more optimal way

**Comment by yuanshh** [comment]
OK，it works. 
Thanks a lot for your patiently reply!
