### ISSUE TITLE
Custom DMI term not calculating energy

### ISSUE THREAD

**Issue by mlittlehales** [computationalmodelling/fidimag#160]
Hi, I want to write a custom DMI term where you can simply change the DMI constant for 3 orthogonal directions to get effectively an anisotropic DMI. I've tried using the custom DMI type by deriving the DMI vector and inputting this using the dmi_vector='custom' option and specifying the DMI constant in a list. When testing this the DMI energy is not calculated even with equal constants (equivalent to bulk DMI) and so the system relaxes to a field polarised state.

My code is written as 
vector = [-1.,0,0,
1.,0,0,
0,0,0,
0,0,0,
0,0,0,
0,0,0,
0,0,0,
0,0,0,
0,-1.,0,
0,1.,0,
0,0,0,
0,0,0,
0,0,0,
0,0,0,
0,0,0,
0,0,0,
0,0,-1.,
0,0,1.]
sim.add(DMI([D,D,D], dmi_type='custom', dmi_vector = vector))

Any variation of this leads to the same result where the DMI energy isn't calculated and the text file output reads the following for every timestep
![image](https://user-images.githubusercontent.com/95351287/144227434-55d8d8e2-a4a3-4ff9-8974-cbd789ea8847.png)

This should still lead to the same results as a bulk DMI term but regardless of the vector I input, with more than one DMI constant, the  energy isn't calculated. Is this a minor syntax problem or something deeper? 

Thanks

**Comment by mlittlehales** [comment]
I initialise the magnetisation using a triple-q model to get a skyrmion lattice. I'll attach a version of the code i have been using to do this. I have just tried that example again and i get the same result as i previously said where the DMI energy isn't calculated. However, if i quote the DMI constant as just being a single value rather than a list it does calculate the DMI energy, maybe this is the issue?


[anis_test.txt](https://github.com/computationalmodelling/fidimag/files/7636014/anis_test.txt)

**Comment by davidcortesortuno** [comment]
I think I found the problem, thanks for reporting this. Can you pull the code (I just updated the DMI class) and try your example again?

**Comment by mlittlehales** [comment]
Pulled the code and rebuild fidimag but it still doesn't calculate the DMI energy

**Comment by davidcortesortuno** [comment]
I see, can you write here a minimal example so I can try to fix the code?

**Comment by mlittlehales** [comment]
So this is the code i've been using to test.

`from fidimag.micro import Sim
from fidimag.common import CuboidMesh
from fidimag.micro import UniformExchange, Demag, DMI, Zeeman
from fidimag.common import plot
import matplotlib.pyplot as plt
import numpy as np

sim_name = 'anis_test'

d = 70
t = 5

dx = dy = dz = 5

mesh = CuboidMesh(nx=int(d/dx), ny=int(d/dy), nz=int(t/dz), dx=dx, dy=dy, dz=dz, unit_length=1e-9)

def Ms_function(Ms):
    return Ms

shift = 2 * np.pi/34.5e-9 
def init_m(pos):
    x,y,z = pos
    x,y,z = x * 2 * np.pi/69e-9, y * 2 * np.pi/69e-9, z * 2 * np.pi/69e-9
    # First helix
    x_out = 0 + (0 * x)
    y_out = 0 + np.cos(x + shift)
    z_out = 0 + np.sin(x + shift)
    # Second Helix
    x_out = x_out - (np.sqrt(3) * np.cos((x/2 + ((np.sqrt(3)/2) * y))))
    y_out = y_out + np.cos((x/2 + ((np.sqrt(3)/2) * y)))
    z_out = z_out + np.sin((x/2 + ((np.sqrt(3)/2) * y)))
    # Third Helix
    x_out = x_out - (np.sqrt(3) * np.cos((-x/2 + ((np.sqrt(3)/2) * y))))
    y_out = y_out - np.cos((-x/2 + ((np.sqrt(3)/2) * y)))
    z_out = z_out + np.sin((-x/2 + ((np.sqrt(3)/2) * y)))
    return (x_out,y_out, z_out)
	
Ms = 3.84e5  # saturation magnetisation (A/m)
A = 8.78e-12  # exchange energy constant (J/m)
D = 1.58e-3  # Dzyaloshinkii-Moriya energy constant (J/m**2)
alpha = 1  # Gilbert damping
gamma = 2.211e5  # gyromagnetic ration (m/As)

sim = Sim(mesh, name=sim_name)
sim.Ms = Ms_function(Ms)
sim.driver.alpha = alpha
sim.driver.gamma = gamma

sim.add(UniformExchange(A=A))
sim.add(Zeeman(H0=(0,0,-10e3)))
sim.add(DMI([D],dmi_type='custom',dmi_vector=[0, -1., 0,  # -x neighbour
                               0, 1., 0,   # +x
                               1., 0, 0,   # -y
                               -1., 0, 0,  # +y
                               0, 0, 0,    # -z  NO DMI in
                               0, 0, 0     # +z  z-dir
                               ]))
sim.set_m(init_m)

sim.driver.relax(dt=1e-13, stopping_dmdt=0.01, max_steps=10000,
                 save_m_steps=None, save_vtk_steps=None, printing=False)
`
Then i open the text file that outputs from the driver to look at the energy contributions and the DMI energy is 0, i attach the outputted file too

[anis_test.txt](https://github.com/computationalmodelling/fidimag/files/7636530/anis_test.txt)
.

**Comment by davidcortesortuno** [comment]
If you have only one DMI, i.e. 18 elements in `dmi_vector` then you should pass `D` as a single value and not a list (this is a "bug" in our code which I can fix soon, but is not critical). If you have more than one DMI you should use a list of `D` values.

Your initial code works fine for me, maybe you were setting something wrongly? This code computes a non-zero DMI energy:

```python
import numpy as np
import fidimag as f


m = f.common.CuboidMesh(1, 1, 1, 10, 1, 1)

sim = f.micro.Sim(m)
sim.set_Ms(1)

vector = [-1.,0,0,
          1.,0,0,
          0,0,0,
          0,0,0,
          0,0,0,
          0,0,0,
          0,0,0,
          0,0,0,
          0,-1.,0,
          0,1.,0,
          0,0,0,
          0,0,0,
          0,0,0,
          0,0,0,
          0,0,0,
          0,0,0,
          0,0,-1.,
          0,0,1.]

# sim.set_m([1, 1, 1.])
sim.set_m(lambda r: [0, 1, 1] if r[0] < 5 else [0, -1, 0])
D = 0.5
sim.add(f.micro.DMI([D, D, D], dmi_type='custom', dmi_vector=vector))
print(sim.mesh.coordinates)
print(sim.spin)
print(sim.get_interaction('DMI').Ds.shape)
print(sim.get_interaction('DMI').n_dmis)

print(sim.compute_energy())
print('Energy', sim.get_interaction('DMI').energy.sum())
```

I get  `Energy -0.35355339059327373`

**Comment by mlittlehales** [comment]
That seems to be working for me now, thank you so much for your help!
