### ISSUE TITLE
Installation issue (make)

### ISSUE THREAD

**Issue by mltm400** [computationalmodelling/fidimag#164]
Exception Error message 
         -----------------------
         No module named 'fidimag.extensions.common_clib'

         System Info
         -----------------------
         Architecture: x86_64
         Platform: macOS-10.16-x86_64-i386-64bit
         Processor: i386

Hi, 
 Please excuse me, as I am a beginner. So I have installed all necessary libraries and folders to the same directory and checked to make sure they are all working fine. My sundials and fft versions are also sttable and up to date. However, when I try running 'make test', all I get is '43 errors and 2 warnings'. I updated  GCC to GCC-10 upon recommendation from another user. 

This is the error I am receiving; 
"
ImportError while importing test module '/Users/ibrahimkhalil/miniconda3/fidimag/tests/field_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
field_test.py:2: in <module>
    from fidimag.common.field import scalar_field, vector_field
../fidimag/common/__init__.py:7: in <module>
    from .helper import init_scalar, init_vector
../fidimag/common/helper.py:1: in <module>
    from fidimag.extensions.common_clib import normalise
E   ModuleNotFoundError: No module named 'fidimag.extensions.common_clib'
"

I have checked my fidimag/extensions/ file and I don't see any of the files they are looking for there. Could someone help me out please. Thanks.

**Comment by mltm400** [comment]
By the way, 
it says to take a step back if you are getting the test errors and just input a 'make' command. 
When I do that, I can't tell whether it's running the same command repeatedly or several commands, as it takes an unbelievable amount of time to finish. I have currently been waiting for 20 minutes and it is still doing the same thing.

**Comment by davidcortesortuno** [comment]
Hi, how did you install Fidimag?  The main steps are

    cd bin
    bash install-fftw.sh
    bash install-sundials.sh
    cd ..
    make

This will build the Fidimag extensions, then you need to add the fidimag folder to your PYTHONPATH env variable

**Comment by davidcortesortuno** [comment]
Closing because of lack of feedback.
