### ISSUE TITLE
track time being spent in integration

### ISSUE THREAD

**Issue by logicabrity** [computationalmodelling/fidimag#20]
I'm working on adding different time integrators to fidimag. Time integration for us typically consists of these computations:
- the effective field
- the RHS of the equation of motion, i.e. solve the LLG

the tasks above are done 1+ times, depending on the time integration scheme
- the new magnetisation state according to the integrator
- (optional) some extra info like a Jacobian times vector product for CVODE

Like Hans says

> We should probably have some kind of reporting how much time is spend on what. We could use the aeon module — just to have a high level understanding of how much time cvode needs to compute that Jacobian, for example.

**Comment by ryanpepper** [comment]
Today at the meeting we were discussing using the newly-built Python-sundials interface:

https://pypi.python.org/pypi/python-sundials/0.5

which may be of interest to you

**Comment by logicabrity** [comment]
Are you sure that's the link you meant to post? Because you said newly-built and that project was last updated 2011.

**Comment by fangohr** [comment]
This is the one: https://github.com/bmcage/odes

**Comment by logicabrity** [comment]
Good, the same project referenced in issue #22 then.

**Comment by ryanpepper** [comment]
Sorry yes, got the wrong one!

**Comment by rpep** [comment]
Is this still an issue or has it been implemented?
