### ISSUE TITLE
use vector_field and scalar_field instead of np.zeros and friends

### ISSUE THREAD

**Issue by logicabrity** [computationalmodelling/fidimag#26]
In `fidimag/common/field.py` the functions `vector_field` and `scalar_field` are defined. I think they convey what they do better than

```
        # actual code from fidimag/micro/llg.py
        self._alpha = np.zeros(self.n, dtype=np.float)
        self._Ms = np.zeros(self.n, dtype=np.float)
        self._Ms_inv = np.zeros(self.n, dtype=np.float)
        self.spin = np.ones(3 * self.n, dtype=np.float)
        self.spin_last = np.ones(3 * self.n, dtype=np.float)
        self._pins = np.zeros(self.n, dtype=np.int32)
        self.field = np.zeros(3 * self.n, dtype=np.float)
        self.dm_dt = np.zeros(3 * self.n, dtype=np.float)
        self._skx_number = np.zeros(self.n, dtype=np.float)
```

Both `vector_field` and `scalar_field` need `v` as optional argument (default set to None so that the function `field` just stops after calling `np.zeros`) to conveniently support this kind of use, since they expect to be set to some value at the moment.

Also replace the uses of `init_vector` and `init_scalar` from `fidimag/common/helper.py`, which relates to #25.

As to why? For one, it makes the code clearer and it also elegantly allows us to change the type of our fields in the future. They're raw np.arrays now, but they don't have to be. Should we decide on something more advanced, we would just need to change the type of object returned by the `field` function.

**Comment by davidcortesortuno** [comment]
The `vector_field` and `scalar_field` should return 1D arrays I guess? since, currently, they are generating `n x 3` or `n x 1` matrices. 

also, If `val` is `None`. I think we can just avoid the `for` loop:

```
    for i, r in enumerate(mesh.coordinates):
        values[i] = f(r)
```

It sounds interesting to use the fields rather than `np.zeros`, but if we used a different object in the future, we have already assumed a structure based on `numpy` arrays, e.g. the `spin` array has the order `mx_0 my_0 mz_0 mx_1 my_1 ...`

**Comment by rpep** [comment]
I don't see this as being a change we're likely to implement in the near future - now the code base is more mature it would be a bad idea to change the interface so much. What do you guys think?
