### ISSUE TITLE
Docker: expose port to be able to serve Jupyter notebook

### ISSUE THREAD

**Issue by fangohr** [computationalmodelling/fidimag#54]
Would be nice to run the Jupyter notebook inside the container, and to connect to it with a browser on the host machine. The `EXPOSE` keyword in the Dockerfile is likely to be the right way forward.

**Comment by takluyver** [comment]
We now have an image `fidimag/notebook` which runs the notebook, separate from the minimal images which only have fidimag. Info here: https://github.com/computationalmodelling/fidimag/tree/master/docker/notebook
