### ISSUE TITLE
Conda install: Version numbering

### ISSUE THREAD

**Issue by ryanpepper** [computationalmodelling/fidimag#56]
If we want to be able to install Fidimag through Conda, we ought to create a release version. We could either checkout a release as is now, or come up with some features or aims such as:

• Tidy up repository
• Make sure code is commented + documented
• Add new feature X

Does anyone have any suggestions for things we need to do before making a release version? Or is it worth creating a release as is. I'm going to take a look at how to do the packaging up of sundials + fftw in order to do this.

**Comment by fangohr** [comment]
I am happy to create a release version as we are - there is always something to improve. We can start modestly with 0.1.0 or so. At the very least, it allows to make progress with the conda installation work. 

[Of course it would be desirable to improve code and documentation but it cannot be done all at once.]
