### ISSUE TITLE
Clean up - tests

### ISSUE THREAD

**Issue by ryanpepper** [computationalmodelling/fidimag#58]
We have files all over the repository called things like integrators_test.py, cuboid_mesh_test.py.

Do we need these, as they're not executed every time? And if so, I think it might be better to move them to the tests directory.

**Comment by fangohr** [comment]
These tests can be run with `make test`. What we run on Travis is only `make test-basics`, for time reasons. So it is good to have those tests.

Regarding the location: I am not sure - I would expect that a file test_x.py would probably start with `import x`, and thus it is practical to have the test file in the same directory as the code to be tested itself. 

So in summary, I don't find it clear that the current setup is wrong.

**Comment by logicabrity** [comment]
The idea was to have proper unit test close to the tested modules. I think our rule of thumb could be: If the test sets up a simulation, it belongs in the test directory instead.
