### ISSUE TITLE
Don't reinvent the wheel - use a library for the MT RNG

### ISSUE THREAD

**Issue by owlas** [computationalmodelling/fidimag#6]
Currently we have a manually coded MT algo for RNG. We could use boost or the GNU scientific library for this.

**Comment by owlas** [comment]
Did this get updated?

**Comment by ryanpepper** [comment]
@ww1g11  You merged in some stuff a while ago, did you fix this?

**Comment by ww1g11** [comment]
We have done a simple comparsion between our own code and GNU RNG, it shows that our own code is faster than the GNU RNG (~5 times fast), considering the extra complexity to introduce a new library, now we still make use of our own codes. 
PS: We haven't try boost since it's quite heavy.

**Comment by ryanpepper** [comment]
I do wonder whether it's worth doing anyway though. It'd be interesting to see whether the RNG generation is even a performance problem in the code - I'd doubt it except maybe in the Monte Carlo case.

Plus there's the advantage of it being better tested than anything we write...

**Comment by ww1g11** [comment]
MT RNG can be implemented within a few lines of code, but the presence of a new library may introduce an extra difficulty in installing fidimag, for example, compiling fidimag in windows system. We need to find a balance between 'reinventing the wheel' and using others' wheel, that's why we haven't wrote our own codes for ode solver and FFT, but implemented a MT RNG.

**Comment by owlas** [comment]
Sorry Weiwei, I wasn't suggesting that yours was not up to scratch. I'm impressed with how easily you threw it together!

I just think that because the algorithm is not that intuitive (at least to me) it is quite hard to read the source. And agree that it isn't rigorously tested.

On the other hand I agree with the dangers of having more dependencies. But there are industry standard and very stable options.

**Comment by ww1g11** [comment]
yes, I agree that our implementation is not well tested and the library should be considered as the first option. A good news is that microsoft is embracing linux/open sources, so the barrier of installing is disappearing, maybe we should try to swith it on in the future (Ryan has wrapped the library using cython already).

**Comment by ryanpepper** [comment]
We could just use Numpy? That's a dependency already

**Comment by owlas** [comment]
But this is called in the C code right?

**Comment by owlas** [comment]
I think.
