### ISSUE TITLE
Error messages when loading magnetisation from file

### ISSUE THREAD

**Issue by davidcortesortuno** [computationalmodelling/fidimag#68]
If we generate an atomistic simulation and save the magnetisation array `mu_s`, then generate another simulation with a different mesh and load the magnetisation file, we get no error message at all. 

This is a MWE,

```Python
import fidimag

# Create simulation
mesh = fidimag.common.CuboidMesh(nx=10, ny=2, nz=1, 
                                                                dx=1, dy=1, dz=1)
sim = fidimag.atomistic.Sim(mesh)
# Set the magnetisation and save it to mu_s.npy
sim.mu_s = 3
np.save('mu_s.npy', sim.mu_s)

# Create another simulation with less elements in the x direction
mesh2 = fidimag.common.CuboidMesh(nx=5, ny=2, nz=1, 
                                                                  dx=1, dy=1, dz=1)
sim2 = fidimag.atomistic.Sim(mesh2)
# Set the magnetisation loading the other simulation file
sim2.mu_s = np.load('mu_s.npy')

print(sim2.mu_s)
```

then we got no error message and the print statement says `array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])`, which means nothing was done.

I guess a similar behaviour is expected from a micromagnetic simulation. We should implement a proper checking of the mesh sizes when loading magnetisation or spin arrays.

**Comment by ryanpepper** [comment]
Fixed in #cc2fb74
