### ISSUE TITLE
Relaxations (sometimes) complete instantly

### ISSUE THREAD

**Issue by mvousden** [computationalmodelling/fidimag#69]
Relaxation operations complete when the difference in magnetisation between integrator time steps reaches a certain value. This can cause some simulations to end prematurely (see MWE below).

In this example the dm/dt, while low initially, increases sharply in time, then decreases gradually as the magnetisation tends to the Zeeman direction. I would like to see the interesting physics.

The first question is whether or not this is really a bug (since the behaviour is somewhat expected), but I would like to "relax" my system to a certain stopping dm/dt.

My proposed solution is to store the last N max(dm/dt) values, and only stop the integration if there is a decreasing trend. I welcome thoughts on this.

``` python
# This script demonstrates that the stopping condition for dm/dt causes
# simulations to stop prematurely in some cases, as the initial dm/dt value is
# too low.
#
# This was run on revision 134b60c.
import fidimag


# Create a single-spin system with only Zeeman energy for simplicity. The
# magnetisation is initialised against the Zeeman direction.
sim = fidimag.micro.Sim(fidimag.common.CuboidMesh(nx=1))
sim.Ms = 9.5e4
sim.add(fidimag.micro.Zeeman([0., 0., -sim.Ms]))
stopping_dmdt = 1  # degree per nanosecond

# Case 1: The relaxation of this system takes one integrator step, and stops
# immediately because dm/dt is below the threshold denoted by the stopping
# criteria.
sim.set_m([1e-4, 1e-4, 1])
sim.relax(stopping_dmdt=stopping_dmdt)
assert abs(sim.spin[2] + 1) < 0.5

# Case 2: This two-stage relaxation mimics a hysteresis loop. The first
# relaxation is identical to the one above with a canted initial spin. However,
# the second relaxation fails for the same reasons as case 1.
sim.set_m([1e-2, 1e-2, 1])
sim.interactions[0].update_field([0., 0., -sim.Ms])
sim.relax(stopping_dmdt=stopping_dmdt)
sim.interactions[0].update_field([0., 0., sim.Ms])
sim.relax(stopping_dmdt=stopping_dmdt)
assert abs(sim.spin[2] - 1) < 0.5
```

**Comment by mvousden** [comment]
`# This script demonstrates that the stopping condition for dm/dt causes
# simulations to stop prematurely in some cases, as the initial dm/dt value is
# too low.
#
# This was run on revision 134b60c.
import fidimag


# Create a single-spin system with only Zeeman energy for simplicity. The
# magnetisation is initialised against the Zeeman direction.
sim = fidimag.micro.Sim(fidimag.common.CuboidMesh(nx=1))
sim.Ms = 9.5e4
sim.add(fidimag.micro.Zeeman([0., 0., -sim.Ms]))
sim.set_m([1e-4, 1e-4, 1])
stopping_dmdt = 1  # degree per nanosecond

# Case 1: The relaxation of this system takes one integrator step, and stops
# immediately because dm/dt is below the threshold denoted by the stopping
# criteria.
sim.set_m([1e-4, 1e-4, 1])
sim.relax(stopping_dmdt=stopping_dmdt)
assert abs(sim.spin[2] + 1) < 1e-3

# Case 2: This two-stage relaxation mimics a hysteresis loop. The first
# relaxation is identical to the one above with a canted initial spin. However,
# the second relaxation fails for the same reasons as case 1.
sim.set_m([1e-2, 1e-2, 1])
sim.interactions[0].update_field([0., 0., -sim.Ms])
sim.relax(stopping_dmdt=stopping_dmdt)
sim.interactions[0].update_field([0., 0., sim.Ms])
sim.relax(stopping_dmdt=stopping_dmdt)
assert abs(sim.spin[2] - 1) < 1e-3
`

**Comment by owlas** [comment]
Would another solution be to have a settling time too?

So 'relaxation' is said to have occurred when the integration step has been sufficiently small for a sufficiently long enough time. This time could even be determined from a rough approximation of the relaxation time constant.

**Comment by ryanpepper** [comment]
I'd had this problem too - I thought it was just me being stupid! 

Oliver's suggestion sounds good

**Comment by fangohr** [comment]
Can I suggest that before we implement anything we study how this is done for NMag and Finmag; just to avoid re-inventing a wheel. (Or finding one that is less round :))

I know that Matteo Franchin (@mfnch) has done a lot of work to deal with this in the Nmag area. I think he has found a good solution, even though I don't remember the details. I think he combined a decrease in energy with a dm/dt based criterion. NMag also spits out a file called 'convergence.txt' or so regularly, which gives information about the current status of the time integration. 

I think we invested most time into this with Nmag. Finmag may have copied some or the best of the ideas, but I am not sure as to whether this is better, comparable or worse than in Nmag.

**Comment by mfnch** [comment]
Sorry guys, I am on holiday at the moment and I haven't been reading emails in the last days.

If I remember correctly, In Nmag convergence is reached when max_r || dm(r)/dt || is lower than a certain value (which we call stopping_dm_dt) for a certain number of consecutive time steps. max_r is the maximum over all the points in space where the magnetisation is defined. || v(r) || represents the norm of the vector v at position r.

Convergence may never be reached if the accuracy of the time integration is not fine enough. In particular, you want to ensure that, in the region of space where the magnetisation changes the most, the time integration error is well below the actual change in magnetisation. It probably makes sense to artificially improve the time integration accuracy when you see that dm/dt * time_step  becomes comparable with the time integration error everywhere in space. One may argue that this should never occur and that - if it does - it is a symptom that the time integration tolerances are too high. This is probably true when one is concerned with the actual dynamics (running with a realistic damping). For hysteresis loop calculations it is convenient to be able to adjust the tolerances on the fly when needed.

**Comment by ryanpepper** [comment]
Here's an example of this in a relaxation I'm looking at. Log scale for clarity - the hlines are dmdt=0.01 and dmdt=0.001, and you can see significant deviation when letting the system relax further

![image](https://cloud.githubusercontent.com/assets/8539474/18272950/cae5c244-7432-11e6-89eb-4a6ec295db45.png)

**Comment by fangohr** [comment]
Thanks, that's useful. Have you tried reducing atol and rtol in the time integrator?

**Comment by ryanpepper** [comment]
Not yet. Given the suggestions, do you think we should set lower defaults for those?

**Comment by fangohr** [comment]
First we should establish that reduced tolerances can indeed fix the problem. It's good news if that is the answer. Then we can think about how we deal with this; but lower defaults are likely to be an outcome.
