### ISSUE TITLE
Mention installation via virtualmicromagnetics in documentation

### ISSUE THREAD

**Issue by fangohr** [computationalmodelling/fidimag#71]
We should point to the virtual micromagnetics project in the installation section, mentioning virtual machines and docker explicitly, maybe also pointing directly to the right download location or something like that.

**Comment by mvousden** [comment]
Once I've built the release containers, I'll update this.

**Comment by mvousden** [comment]
Discussed in #74.

**Comment by rpep** [comment]
No longer relevant
