### ISSUE TITLE
Installation Problems - Sundials

### ISSUE THREAD

**Issue by ryanpepper** [computationalmodelling/fidimag#81]
@davidcortesortuno, @mvousden and I have all run into a problem with building Fidimag which relates to Sundials 2.6.2 installation. On importing, we get the error:
```
'Undefined symbol dcopy_'
```

 which seems to relate to BLAS. 

A workaround is to install Fidimag through an Anaconda environment, and in that case everything seems to work correctly - probably because there's a version of BLAS that is packaged with Anaconda and this is found in the path. However, it would be good to find out exactly what the origin of this error is, because currently, following the standard install procedure, you cannot get Anaconda running on Ubuntu 16.04 in Python 3 installed through apt-get.

**Comment by davidcortesortuno** [comment]
We solved this adding the `lblas` and `lapack` libraries to the `setup.py` file.
