### ISSUE TITLE
Refactor setup.py

### ISSUE THREAD

**Issue by rpep** [computationalmodelling/fidimag#85]
Couple of problems:
a) We're not currently using the correct way to link libraries; Distutils Extension has specifically for this and we're currently using 'extra_link_args'.

b) Currently cannot compile FIDIMAG for use on Iridis due to BLAS and LAPACK compiler flags. Soton HPC advise use of MKL for BLAS, but that needs handling with the link arguments in setup.py. Here we need to:
• Compile Sundials with given BLAS/LAPACK implementation - need to refactor the install-sundials.sh script and add include directories to specific include and library dirs.
• Link BLAS/LAPACK correctly when creating Extension modules.

**Comment by ww1g11** [comment]
A silly question: why the BLAS and LAPACK are needed in fidimag?

**Comment by ryanpepper** [comment]
Sundials uses them behind the scenes for calculations :)

**Comment by ryanpepper** [comment]
@ww1g11 It's not a hard dependency but speeds the calculations up when present.

**Comment by ww1g11** [comment]
that's interesting, it seems that the LAPACK_ENABLE option is off by defaut, if there is a speedup due to lapack then it's worth a try.

**Comment by ryanpepper** [comment]
The build script bin/install-sundials.sh will install it with this enabled :) I don't know if it is enabled if installed through a package manager like apt-get though.

**Comment by ww1g11** [comment]
can we simply disable LAPACK in installing fidimag on Iridis?

**Comment by ryanpepper** [comment]
I suppose so, but I don't know if it's a good idea. The performance report from NAG showed the majority of the time spent in time integrator were in BLAS/LAPACK functions.

**Comment by ww1g11** [comment]
Maybe we can write a test to see whether lapack has an influence on the performance of fidimag.

**Comment by rpep** [comment]
Need to test this but low priority
