### ISSUE TITLE
Add link to read the docs and github repo to webpage

### ISSUE THREAD

**Issue by fangohr** [computationalmodelling/fidimag#9]
http://fidimag.readthedocs.org

and 

https://github.com/computationalmodelling/fidimag

**Comment by owlas** [comment]
David had the github icon. I have added the docs. @davidcortesortuno can you ok the design?

**Comment by fangohr** [comment]
Great. I think the github icon links to fangohr/fidimag, not computationalmodelling/fidimag, otherwise great.

**Comment by owlas** [comment]
Done.
