### ISSUE TITLE
Memory Leak in CVODE Code

### ISSUE THREAD

**Issue by rpep** [computationalmodelling/fidimag#97]
David had some code that was showing a memory leak, and we found after a lot of investigation with valgrind we found the code runs through:

1) The sim object has a function called set_m. This calls a function in the driver class called set_initial_value

2) The driver class creates an NVector object using N_VMake_OpenMP and stores that in the self.u_y variable.

3) The class explicitly destroys self.u_y in the __dealloc__ function, by calling N_VDestroy_OpenMP(self.u_y)

4) However, if set_initial_value is called, self.u_y is overwritten, but the previous self.u_y is never explictly free'd

5) This leads to a leak; we can see this clearly by commenting out the 'self.driver.set_initial_value' function call in set_m for a pathological setup - without this, the growth in memory usage when an NEBM method is called is much lower.

To fix this:
* Need to fix this by explicitly deallocating the self.u_y memory, both in the OpenMP and serial code.

* Also need to fix the broken OpenMP calling in the NEBM code.

**Comment by davidcortesortuno** [comment]
This should be fixed by Merge #98
